version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - desm
  - envcredible
  - envrw
  - oxlint
  - RABBITMQ
  - Substate
  - tsdown
  - tsgo
ignoreWords: []
import: []
