import { z } from "zod";
import {
  INFRASTRUCTURE_DEFAULTS,
  INFRASTRUCTURE_DESCRIPTIONS,
  INFRASTRUCTURE_LIMITS,
  INFRASTRUCTURE_MESSAGES,
} from "../../../shared/infrastructure";

const schema = z
  .number()
  .describe(INFRASTRUCTURE_DESCRIPTIONS.PROMETHEUS_PORT)
  .int({ error: INFRASTRUCTURE_MESSAGES.PROMETHEUS_PORT_INT })
  .min(INFRASTRUCTURE_LIMITS.PROMETHEUS_PORT_MIN, { error: INFRASTRUCTURE_MESSAGES.PROMETHEUS_PORT_MIN })
  .max(INFRASTRUCTURE_LIMITS.PROMETHEUS_PORT_MAX, { error: INFRASTRUCTURE_MESSAGES.PROMETHEUS_PORT_MAX })
  .default(INFRASTRUCTURE_DEFAULTS.PROMETHEUS_PORT);

export const prometheusPortSchema = schema;
export const PROMETHEUS_PORT = prometheusPortSchema;
