# Name of the package.json at the repository root. The script walks upward
# until it finds a matching package name.
repoPackageName: "@e-n-v/repo"

# Root-relative path to the directory that hosts all publishable code.
packagesDir: packages

# Name of the package inside packagesDir that acts as the distribution bundle.
bundlePackageName: env

# Dependency name prefixes that we skip when checking for bundle coverage. Use
# this to mark bundled packages that are not meant to ship. The same prefixes
# are also blocked from appearing in the bundle's own dependency list.
bundledPrefixes:
  - "@e-n-v/"

# Dependencies that are allowed to exist only in the bundle package without
# being present in any other workspace package.
bundleOnlyDependencies: []
