name: ci

on:
  pull_request:
    - "*/*"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Check types
        run: bun run check:types

      - name: Check formatting
        run: bun run check:format

      - name: Test
        run: bun run test
